# Generated by Django 3.2 on 2025-03-03 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipe', '0008_alter_recipe_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeShortLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(max_length=2000, unique=True)),
                ('short_code', models.CharField(blank=True, max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='short_link', to='recipe.recipe', verbose_name='Рецепт')),
            ],
            options={
                'verbose_name': 'Короткая ссылка на рецепт',
                'verbose_name_plural': 'Короткие ссылки на рецепты',
                'ordering': ['-created_at'],
                'default_related_name': 'short_link',
            },
        ),
        migrations.AddConstraint(
            model_name='recipeshortlink',
            constraint=models.UniqueConstraint(fields=('original_url', 'short_code'), name='unique_short_link'),
        ),
    ]
