# Generated by Django 3.2 on 2025-03-15 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0008_alter_recipe_is_active'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recipeshortlink',
            name='unique_short_link',
        ),
        migrations.AlterField(
            model_name='recipeshortlink',
            name='recipe',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='short_link', to='recipe.recipe', verbose_name='Рецепт'),
        ),
        migrations.AddConstraint(
            model_name='recipeshortlink',
            constraint=models.UniqueConstraint(fields=('recipe', 'short_code'), name='unique_short_link'),
        ),
    ]
