# Generated by Django 3.2 on 2025-02-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipe', '0001_initial'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='recipes',
            field=models.ManyToManyField(blank=True, null=True, to='recipe.Recipe'),
        ),
    ]
