# Generated by Django 3.2 on 2025-02-22 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_initial'),
        ('cart', '0002_cart_recipes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='recipes',
            field=models.ManyToManyField(blank=True, to='recipe.Recipe'),
        ),
    ]
