# Generated by Django 3.2 on 2025-02-22 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('measurement_unit', models.CharField(choices=[('горсть', 'Горсти'), ('капля', 'Капли'), ('веточка', 'Веточки'), ('мл', 'мл'), ('ч. л.', 'Чайные ложки'), ('кусок', 'Куски'), ('банка', 'Банки'), ('г', 'г'), ('стакан', 'Стаканы'), ('щепотка', 'Щепотки'), ('батон', 'Батоны'), ('ст. л.', 'Столовые ложки'), ('шт.', 'Штуки')], default='г', max_length=15)),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=1, max_digits=999)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingredient.ingredient')),
            ],
        ),
    ]
