# Generated by Django 3.2 on 2025-02-28 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_auto_20250227_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Прохождение модерации', verbose_name='Активен'),
        ),
    ]
