# Generated by Django 3.2 on 2025-03-03 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_auto_20250302_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Модерация', verbose_name='Активен'),
        ),
    ]
