# Generated by Django 3.2 on 2025-02-22 21:47

import django.contrib.auth.validators
from django.db import migrations, models

import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'Пользователь с таким именем пользователя уже существует.'}, help_text='Обязательное поле. Не более 150 символов. Можно использовать буквы, цифры и спецсимволы: @/./+/-/_', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator, users.validators.NotMeValidator], verbose_name='Имя пользователя'),
        ),
    ]
