# Generated by Django 3.2 on 2025-02-23 00:10

from django.db import migrations

import users.managers


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.managers.CustomManager()),
            ],
        ),
    ]
