# Generated by Django 3.2 on 2025-02-27 01:30

import django.core.validators
from django.db import migrations, models

import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Не более 10.0 Мб', null=True, upload_to='users/avatars/', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'Пользователь с таким именем пользователя уже существует.'}, help_text='Обязательное поле. Не более 150 символов. Можно использовать буквы, цифры и спецсимволы: @/./+/-/_', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Некорректный username', regex='^[\\w.@+-]+\\Z'), users.validators.NotMeValidator], verbose_name='Имя пользователя'),
        ),
    ]
