# Generated by Django 3.2 on 2025-03-03 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cart_recipes'),
        ('users', '0004_auto_20250227_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cart',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='cart.cart', verbose_name='Корзина'),
        ),
    ]
